class EN {
  static Map<String, String> get languages{
    return {
        "footer_home":"HOME",
        "footer_category":"CATEGORY",
        "footer_search":"SEARCH",
        "footer_setting":"SETTING",
        "more":"More",
        "discover":"Discover",
        "your_favorite":"Your favorite",
        "search_page": "Search. . .",
        "search_shoes": "Search shoes. . .",
        "my_wishlist":"My Wishlist",
        "shipping_address":"Shipping Address",
        "allow_notification":"Allow Notification",
        "currencies":"Currencies",
        "welcome_signin":"Welcome, Sign in to your account",
        "see_all":"See all",
        "welcome_back":"Welcome Back",
        "please_signin_to_continue":"Please signin to continue",
        "signup":"SIGNUP",
        "enter_your_email":"Enter your email here",
        "enter_your_password":"Enter your password here",
        "email":"EMAIL",
        "enter_username":"Enter your username here",
        "already_have_account":"Already have account?",
        "no_have_account":"Don\'t have an account?",
        "by_sign_up":"By sign up you accept the",
        "pri_po":" Privacy policy",
        "pri_policy":"Privacy policy",
        "checkout_cart_btn":"check-out",
        "enter_town_or_city":"Please enter your town or city",
        "enter_street_name":"Please enter your street name",
        "enter_house_number":"Please enter your house number",
        "enter_phone":"Please enter your phone number",
        "enter_postcode":"Please enter your postcode",
        "order_noted":'order_note',
        "favotite":'FAVORITE',
        "order_id":"ORDER ID",
        "status":"Status",
        "amount":"Amount",
        "order_detail":"Order Detail",
        "order_status":"Order Status",
        "enter_username_signup":"Please enter your username",
        "enter_email_signup":"Please enter your email",
        "enter_password_signup":"Please enter your password",
        "logoutMenu":"Logout",
        "welcome_signout":"Please click here to signout",
        "form_forgot_pass":"ForgotPassword",
        "attention":"Attention",
        "warning_message":"Warning message!",
        "ask_question_logout":"Do you want to Log out?",
        "validate_email":"Your email are incorrect format",
        "invalid_phone":"Invalid phone number",







        "new": "New",
        "new_release": "New Release",
        "featured": "Featured",
        "featured_menu": "Featured Release",
        "apply": "Apply",
        "enter_coupon_discount": "Enter coupon/discount code",
        "total": "Total",
        "checkout": "Checkout",
        "notifications": "Notifications",
        "liked": "Liked",
        "items": " items",
        "item": " item",
        "no_product": "No any product",
        "login": "Login",
        "username_email": "Username or Email",
        "password": "Password",
        "forgot_password": "Forgot Password ?",
        "create_account": "Create Account",
        "don_have_account": "Don't have an account ?",
        "search": "Search",
        "filter": "FILTER",
        "shoes_name": "Shoes name etc ...",
        "brand": "BRAND",
        "shoes_size": "SHOES SIZE",
        "price_range": "PRICE RANGE",
        "min": "Min",
        "ok": "Ok",
        "max": "Max",
        "fail": "Fail",
        "some_when_wrong": "Something went wrong please try again.",
        "success": "Success",
        "account_success": "Account update successfully",
        "cancel": "Cancel",
        "apply_filter": "Apply Filter",
        "upcoming": "Upcoming",
        "upcoming_menu": "Upcoming Releases",
        "faq": "FAQ",
        "tracking": "Order Tracking",
        "order_tracking": "Order Tracking",
        "terms_conditions": "Terms and conditions",
        "how_app": "How to use App",
        "live_chat": "Live Chat",
        "my_orders": "My Orders",
        "address": "Address",
        "settings": "Settings",
        "placed_on": "Placed On",
        "password_success": "Password update successfully",
        "account": "Account",
        "address_updated": "Address updated",
        "error": "Error!",
        "save_change": "SAVE CHANGES",
        "logout": "LOGOUT",
        "language": "Language",
        "current_password": "Current Password",
        "new_password": "New password",
        "confirm_password": "Confirm new password",
        "currency": "Currency",
        "first_name": "First name",
        "last_name": "Last name",
        "middle_name": "Middle name",
        "country": "Country",
        "region": "Region",
        "is_required": "is required",
        "town_city": "Town / City",
        "the_address": "The address that shipping company will ship to.",
        "street_name": "Street name",
        "house_number": "House number",
        "post_zip": "Postcode/Zip",
        "email_address": "Email address",
        "phone_num": "Phone number",
        "if_dont_know": "If you don't know your address zipcode add 0000",
        "next": "Next",
        "billing": "Billing",
        "invalid": "Invalid",
        "shipping": "Shipping",
        "important_notice": "Important Notice!",
        "due_to": "Due to shipping company requirements you have to fill",
        "your_name": "- Your First name, Middle name, Last name, same as your ID card correctly.",
        "your_address": "- Shipping House number, Street name correctly.",
        "other_wise": "Otherwise the shipment will be delay or on hold",
        "confirm": "Confirm",
        "review": "Review",
        "subtotal": "Subtotal",
        "coupon_discount": "Coupon Discount",
        "order_note": "Order note, e.g. special notes for delivery.",
        "payment": "Payment",
        "back": "Back",
        "credit_card": "Credit/Debit Card",
        "your_personal": "Your personal data will be used to process your order, support your experience throughout this application, and for other purposes described in our \n",
        "privacy_policy": "Privacy And policy",
        "i_have_read": "I have read and agree to the application ",
        "pay_now": "Pay Now",
        "send_a_message": "Write a message...",
        "caption": "Caption",
        "send": "SEND",
        "billing_address": "Billing Address",
        "release": "Releases",
        "category": "Category",
        "invalid_credentials": "Invalid credentials",
        "up_incurrect": "Username or password is incurrect.",
        "your_acc_success": "Your account was created successfully.",
        "warning": "Warning",
        "reset_password": "Reset password",
        "haved_account": "Already have an account ?",
        "dont_acc": "Don't have an account ?",
        "your_username": "Your username",
        "your_email": "Your email",
        "repeat_password": "Repeat Password",
        "repeat_not_matching_password": "Repeat Password is not matching the password",
        "sign_up": "Sign Up",
        "delete": "Delete",
        "something_when": "Something went wrong, please try again",
        "coupon": "Coupon:",
        "price": "Price",
        "sorry": "Sorry!",
        "coupon_invalid": "The coupon is invalid.",
        "size_u": "SIZE:",
        "out_stock": "The product is out of stock.",
        "enter_your": "Please enter your first name same as your ID card",
        "only_english": "Only english letters allowed.",
        "enter_middle_name": "Please enter your middle name same as your ID card",
        "enter_last_name": "Please enter your last name same as your ID card",
        "cannot_checkout": "Checkout cannot process with these address,",
        "please_try_again": "please check try again.",
        "contact_us": "Contact Us",
        "photos": "Photos",
        "description": "Description",
        "reviews": "Reviews",
        "video": "Video",
        "sell": "Sell",
        "cancel_order": "Cancel Order",
        "are_you_sure": "Are you sure?",
        "no": "No",
        "yes": "Yes",
        "no_found": "No results found.",
        "searching": "Searching, please wait...",
        "is_incurrect": "Username or password is incurrect.",
        "register": "Register",
        "username": "Username",
        "enter_password": "Enter your password",
        "tracking_number": "Tracking Number",
        "search_by": "Search by country name or dial code",
        "write_something": "Write something ...",
        "field_required": "This field is required",
        "thank_for_review": "Thank you for the review",
        "close": "Close",
        "add_to_cart": "Add to Cart",
        "buy_now": "Buy Now",
        "size": "SIZE",
        "size_chart": "Size Chart",
        "sign_out": "Sign Out",
        "contact_instead": "Contact us instead?",
        "so_happy": "We are so happy to hear :)",
        "so_sad": "We're sad to hear :(",
        "submit": "SUBMIT",
        "add_review": "Add Review",
        "if_you_have": "If you have this shoe with original recipt and you want to sell it",
        "nike_size": "NIKE SIZES",
        "adias_sizes": "ADIDAS SIZES",
        "maintenance": "This screen is under maintenance!\\nPlease check back later.",
        "cart_added": "Cart added",
        "successfully_added": "Item successfully added to your cart.",
        "welcom_support_message": "Hello! Welcome to king-kicks.com!\nThis is king-kicks customers service team, How may we assist you today?",
        "search_your_tracking": "Search your tracking number",
        "enter_your_order_number": "Enter your order number",
        "find_my_tracking": "Find my tracking number",
        "how_can_i_find": "How can I find my order ID?",
        "click_here": "Click Here",
        "loading": "Loading...",
        "pls_enter_name": "Please enter Username or Email",
        "sign_in": "Sign In",
        "or": "or",
        "log_google": "Log In with Google",
        "log_apple": "Log In with Apple",
        "app_maintenance": "This screen is under maintenance!\nPlease check back later.",
        "log_to_review": "Login to Add Review",
        "u_is_re": "Username is required",
        "signup_google": "Sign Up with Google",
        "signup_apple": "Sign Up with Apple",
        "by_sign_accept": "By signing up you accept the",
        "term_services": "Terms of Service",
        "and": " and",
        "b_n_s": "Buy and Sell",
        "a_sn": "Authentic Sneakers",
        "tracking_shipment": "Tracking Your Shipment",
        "pls_en_tr": "Please enter your order number",
        "or_num": "Order number",
        "not_found": "Not Found",
        "som_wrong": "Something when wrong, please try again",
        "or_no": "Order No.",
        "note": "Note",
        "or_status": "Order Status",
        "make_payment": "Make Payment",
        "PendingPayment": "Pending Payment",
        "Pleasecompletepayment": "Please complete payment.",
        "OrderConfirmed": "Order Confirmed",
        "we_pro_ur_or": "We has been processing your order.",
        "shipmentinformation": "Collecting shipment information",
        "Collectingyourshipment": "Collecting your shipment information.",
        "Onhold": "On hold",
        "yourOnhold": "Your order is on hold.",
        "Refunded": "Refunded",
        "yourRefunded": "Your order has been refunded.",
        "Arranging": "Arranging",
        "yourArranging": "Arranging your order.",
        "Pickup": "Pickup",
        "dhlPickup": "DHL just collected your shipment.",
        "Shipped": "Shipped",
        "yourShipped": "Your order is shipping.",
        "Completed": "Completed",
        "yourCompleted": "You received your shipment.",
        "Ordercancelled": "Order cancelled",
        "yourOrdercancelled": "Order cancelled by customer.",
        "enter_your_billing_firstname": "Please enter your first name same as your ID card",
        "enter_your_billing_middle": "Please enter your middle name same as your ID card",
        "enter_your_billing_last": "Please enter your last name same as your ID card",
        "the_billing_address": "The address that shipping company will ship to.",
        "the_billing_the_house": "The house address that shipping company will ship to.",
        "not_know_billing_shipcode": "If you don't know your address zipcode add 0000",
        "billing_email_address": "We will send order information to this email address.",
        "the_shipping_address": "The address that shipping company will ship to.",
        "the_shipping_the_house": "The house address that shipping company will ship to.",
        "not_know_shipping_shipcode": "If you don't know your address zipcode add 0000",
        "shipping_email_address": "We will send order information to this email address.",
        "enter_your_shipping_firstname": "Please enter your first name same as your ID card",
        "enter_your_shipping_middle": "Please enter your middle name same as your ID card",
        "enter_your_shipping_last": "Please enter your last name same as your ID card",
        "out_of_stock": "OUT OF STOCK",
        "hello_welcome": "Hello! Welcome to king-kicks.com!",
        "this_is_customer": "This is king-kicks customers service team,",
        "hom_may_we": "How may we assist you today?"
    };
  }
}